[03/Apr/2016:09:35:33]  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/sessions.py", line 874, in init
    storage_class.setup(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/sessions.py", line 484, in setup
    kwargs['storage_path'] = os.path.abspath(kwargs['storage_path'])
KeyError: 'storage_path'
[03/Apr/2016:09:35:33] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 661, in respond
    self.hooks.run('before_request_body')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
KeyError: 'storage_path'
[03/Apr/2016:09:35:33] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:16:23] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:16:23] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 18, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
NameError: global name 'Temperature' is not defined
[03/Apr/2016:12:18:20] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:18:20] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 18, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
NameError: global name 'Temperature' is not defined
[03/Apr/2016:12:44:47] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:44:47] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/temperature.py", line 19, in get_last_24_hours
    return session.query(Temperature).filter(Temperature.readingDate >= datetime.now() + datetime.timedelta(days=1)).order_by(Temperature.readingDate)
AttributeError: 'module' object has no attribute 'now'
[03/Apr/2016:12:47:36] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:47:36] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/temperature.py", line 19, in get_last_24_hours
    return session.query(Temperature).filter(Temperature.readingDate >= datetime.now() + datetime.timedelta(days=1)).order_by(Temperature.readingDate)
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[03/Apr/2016:12:48:18] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:48:18] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/temperature.py", line 20, in get_last_24_hours
    return session.query(Temperature).filter(Temperature.readingDate >= datetime.now() + datetime.timedelta(days=1)).order_by(Temperature.readingDate)
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[03/Apr/2016:12:50:18] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:50:18] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/temperature.py", line 19, in get_last_24_hours
    return session.query(Temperature).filter(Temperature.readingDate >= datetime.now() + datetime.timedelta(days=1)).order_by(Temperature.readingDate)
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
[03/Apr/2016:12:54:51] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:54:51] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "readingView"."readingDate" AS "readingView_readingDate", "readingView"."airTemperature" AS "readingView_airTemperature", "readingView"."heaterTemperature" AS "readingView_heaterTemperature" \nFROM "readingView" \nWHERE "readingView"."readingDate" >= ? ORDER BY "readingView"."readingDate"'] [parameters: ('2016-04-04 12:54:51.671239',)]
[03/Apr/2016:12:58:28] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:12:58:28] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2749, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2740, in _connection_from_session
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
OperationalError: (sqlite3.OperationalError) unable to open database file
[03/Apr/2016:13:00:05] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:13:00:05] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "readingView"."readingDate" AS "readingView_readingDate", "readingView"."airTemperature" AS "readingView_airTemperature", "readingView"."heaterTemperature" AS "readingView_heaterTemperature" \nFROM "readingView" \nWHERE "readingView"."readingDate" >= ? ORDER BY "readingView"."readingDate"'] [parameters: ('2016-04-04 13:00:05.339017',)]
[03/Apr/2016:13:02:01] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:13:02:01] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "readingView"."readingDate" AS "readingView_readingDate", "readingView"."airTemperature" AS "readingView_airTemperature", "readingView"."heaterTemperature" AS "readingView_heaterTemperature" \nFROM "readingView" \nWHERE "readingView"."readingDate" >= ? ORDER BY "readingView"."readingDate"'] [parameters: ('2016-04-04 13:02:01.914710',)]
[03/Apr/2016:13:24:44] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:13:24:44] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView" \nWHERE "sensorsReadingView"."readingDate" >= ? ORDER BY "sensorsReadingView"."readingDate"'] [parameters: ('2016-04-04 13:24:44.471130',)]
[03/Apr/2016:13:27:33] HTTP 
Request Headers:
  COOKIE: beaker.session.id=8971256a022544008f1477cdf4e7acb2
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  REFERER: http://192.168.1.183:7070/
  ACCEPT-ENCODING: gzip, deflate
[03/Apr/2016:13:27:33] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView" \nWHERE "sensorsReadingView"."readingDate" >= ? ORDER BY "sensorsReadingView"."readingDate"'] [parameters: ('2016-04-04 13:27:33.803550',)]
[08/Apr/2016:20:40:28] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:20:40:28] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView" \nWHERE "sensorsReadingView"."readingDate" >= ? ORDER BY "sensorsReadingView"."readingDate"'] [parameters: ('2016-04-09 20:40:28.380668',)]
[08/Apr/2016:20:42:01] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:20:42:01] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView" \nWHERE "sensorsReadingView"."readingDate" >= ? ORDER BY "sensorsReadingView"."readingDate"'] [parameters: ('2016-04-09 20:42:01.384290',)]
[08/Apr/2016:20:47:32] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:20:47:32] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView" \nWHERE "sensorsReadingView"."readingDate" >= ? ORDER BY "sensorsReadingView"."readingDate"'] [parameters: ('2016-04-09 20:47:32.572741',)]
[08/Apr/2016:20:48:52] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:20:48:52] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView"']
[08/Apr/2016:20:54:50] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:20:54:50] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView"']
[08/Apr/2016:21:03:52] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:21:03:52] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView"']
[08/Apr/2016:21:07:07] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:21:07:07] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView"']
[08/Apr/2016:21:10:20] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:21:10:20] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView"']
[08/Apr/2016:21:28:56] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[08/Apr/2016:21:28:56] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView"']
[09/Apr/2016:13:22:20] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:13:22:20] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView"']
[09/Apr/2016:15:56:25] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:15:56:25] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 20, in last_24_hours
    for temperature in Temperature.get_last_24_hours(db):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (sqlite3.DatabaseError) file is encrypted or is not a database [SQL: u'SELECT "sensorsReadingView"."readingDate" AS "sensorsReadingView_readingDate", "sensorsReadingView"."airTemperature" AS "sensorsReadingView_airTemperature", "sensorsReadingView"."heaterTemperature" AS "sensorsReadingView_heaterTemperature" \nFROM "sensorsReadingView"']
[09/Apr/2016:16:10:15] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:10:15] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 26, in last_24_hours
    temperature.append(node)
AttributeError: 'Temperature' object has no attribute 'append'
[09/Apr/2016:16:12:49] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:12:49] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 26, in last_24_hours
    temperature.append(node)
AttributeError: 'Temperature' object has no attribute 'append'
[09/Apr/2016:16:15:05] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:15:05] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 26, in last_24_hours
    temperature.append(node)
AttributeError: 'dict' object has no attribute 'append'
[09/Apr/2016:16:17:38] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:17:38] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 26, in last_24_hours
    temperature.append(node)
UnboundLocalError: local variable 'node' referenced before assignment
[09/Apr/2016:16:19:13] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:19:13] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 26, in last_24_hours
    temperatures.append(node)
UnboundLocalError: local variable 'node' referenced before assignment
[09/Apr/2016:16:28:30] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:28:30] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 675, in respond
    response.finalize()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 947, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 908, in collapse_body
    for chunk in self.body:
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 289, in compress
    for line in body:
  File "/usr/lib/python2.7/json/encoder.py", line 427, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 435, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 3, 25, 14, 46, 46) is not JSON serializable
[09/Apr/2016:16:28:42] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:28:42] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 675, in respond
    response.finalize()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 947, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 908, in collapse_body
    for chunk in self.body:
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 289, in compress
    for line in body:
  File "/usr/lib/python2.7/json/encoder.py", line 427, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 435, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 3, 25, 14, 46, 46) is not JSON serializable
[09/Apr/2016:16:28:48] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:28:48] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 675, in respond
    response.finalize()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 947, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 908, in collapse_body
    for chunk in self.body:
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 289, in compress
    for line in body:
  File "/usr/lib/python2.7/json/encoder.py", line 427, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 435, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 3, 25, 14, 46, 46) is not JSON serializable
[09/Apr/2016:16:29:33] HTTP 
Request Headers:
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; rv:45.0) Gecko/20100101 Firefox/45.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
[09/Apr/2016:16:29:33] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 675, in respond
    response.finalize()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 947, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 908, in collapse_body
    for chunk in self.body:
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 289, in compress
    for line in body:
  File "/usr/lib/python2.7/json/encoder.py", line 424, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 435, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 3, 25, 14, 46, 46) is not JSON serializable
[10/Apr/2016:10:54:52] HTTP 
Request Headers:
  Content-Length: 62
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[10/Apr/2016:10:54:52] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 54, in reading_in_range
    for temperature in Temperature.get_reading_inrange(db, fromDate, toDate):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/temperature.py", line 35, in get_reading_inrange
    return session.query(Temperature).filter(Temperature.readingDate >= fromDateTime and Temperature.readingDate <= toDateTime).order_by(Temperature.readingDate)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 2745, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
[10/Apr/2016:10:58:01] HTTP 
Request Headers:
  Content-Length: 62
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[10/Apr/2016:10:58:01] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 54, in reading_in_range
    for temperature in Temperature.get_reading_inrange(db, fromDate, toDate):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/temperature.py", line 35, in get_reading_inrange
    return session.query(Temperature).filter(Temperature.readingDate >= fromDateTime, Temperature.readingDate <= toDateTime).order_by(Temperature.readingDate)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 2745, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
[10/Apr/2016:10:59:15] HTTP 
Request Headers:
  Content-Length: 62
  REFERER: http://192.168.1.183:7070/
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: application/json, text/javascript, */*; q=0.01
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[10/Apr/2016:10:59:15] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 54, in reading_in_range
    for temperature in Temperature.get_reading_inrange(db, fromDate, toDate):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/temperature.py", line 35, in get_reading_inrange
    def get_reading_inrange(session, fromDateTime, toDateTime):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 2745, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
[24/Apr/2016:13:47:51] HTTP 
Request Headers:
  CONNECTION: keep-alive
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:47:51] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 85, in powerConsumptionLastMonth
    for powerConsumption in Electricity.get_this_month(db):
NameError: global name 'Electricity' is not defined
[24/Apr/2016:13:48:51] HTTP 
Request Headers:
  CONNECTION: keep-alive
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:48:51] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 85, in powerConsumptionLastMonth
    for powerConsumption in ElectricityView.get_this_month(db):
NameError: global name 'ElectricityView' is not defined
[24/Apr/2016:13:49:36] HTTP 
Request Headers:
  CONNECTION: keep-alive
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:49:36] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 85, in powerConsumptionLastMonth
    for powerConsumption in ElectricityView.get_this_month(db):
NameError: global name 'ElectricityView' is not defined
[24/Apr/2016:13:50:07] HTTP 
Request Headers:
  CONNECTION: keep-alive
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:50:07] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 85, in powerConsumptionLastMonth
    for powerConsumption in ElectricityView.get_this_month(db):
NameError: global name 'ElectricityView' is not defined
[24/Apr/2016:13:50:53] HTTP 
Request Headers:
  CONNECTION: keep-alive
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:50:53] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 85, in powerConsumptionLastMonth
    for powerConsumption in ElectricityView.get_this_month(db):
NameError: global name 'ElectricityView' is not defined
[24/Apr/2016:13:52:19] HTTP 
Request Headers:
  CONNECTION: keep-alive
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:52:19] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 86, in powerConsumptionLastMonth
    for powerConsumption in ElectricityView.get_this_month(db):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityView.py", line 26, in get_this_month
    return session.query(ElectricityView).filter(Electricity.readingDate >= firstDayOfMonth).order_by(Electricity.readingDate)
NameError: global name 'Electricity' is not defined
[24/Apr/2016:13:53:03] HTTP 
Request Headers:
  CONNECTION: keep-alive
  PRAGMA: no-cache
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: no-cache
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:53:03] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 86, in powerConsumptionLastMonth
    for powerConsumption in ElectricityView.get_this_month(db):
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityView.py", line 26, in get_this_month
    return session.query(ElectricityView).filter(ElectricityView.readingDate >= firstDayOfMonth).order_by(ElectricityView.readingDate)
NameError: global name 'Electricity' is not defined
[24/Apr/2016:13:54:19] HTTP 
Request Headers:
  CONNECTION: keep-alive
  PRAGMA: no-cache
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: no-cache
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:54:19] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 88, in powerConsumptionLastMonth
    "readingDate": temperature.readingDate,
NameError: global name 'temperature' is not defined
[24/Apr/2016:13:55:24] HTTP 
Request Headers:
  CONNECTION: keep-alive
  PRAGMA: no-cache
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: no-cache
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:55:24] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 675, in respond
    response.finalize()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 947, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 908, in collapse_body
    for chunk in self.body:
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 289, in compress
    for line in body:
  File "/usr/lib/python2.7/json/encoder.py", line 424, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 435, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Column(None, Text(), table=None) is not JSON serializable
[24/Apr/2016:13:58:12] HTTP 
Request Headers:
  CONNECTION: keep-alive
  PRAGMA: no-cache
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: no-cache
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:13:58:12] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 675, in respond
    response.finalize()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 947, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 908, in collapse_body
    for chunk in self.body:
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 289, in compress
    for line in body:
  File "/usr/lib/python2.7/json/encoder.py", line 424, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 435, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Column(None, Text(), table=None) is not JSON serializable
[24/Apr/2016:14:01:24] HTTP 
Request Headers:
  CONNECTION: keep-alive
  HOST: 192.168.1.183:7070
  UPGRADE-INSECURE-REQUESTS: 1
  CACHE-CONTROL: max-age=0
  Remote-Addr: 192.168.1.194
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  ACCEPT-ENCODING: gzip, deflate, sdch
[24/Apr/2016:14:01:24] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 675, in respond
    response.finalize()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 947, in finalize
    content = self.collapse_body()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 908, in collapse_body
    for chunk in self.body:
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 289, in compress
    for line in body:
  File "/usr/lib/python2.7/json/encoder.py", line 424, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 401, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 325, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 435, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 177, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Column(None, Text(), table=None) is not JSON serializable
[24/Apr/2016:20:15:59] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:15:59] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
NameError: global name 'inputJson' is not defined
[24/Apr/2016:20:16:05] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:16:05] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
NameError: global name 'inputJson' is not defined
[24/Apr/2016:20:16:58] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:16:58] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 23, in addReadingValue
    now = date.today()
NameError: global name 'date' is not defined
[24/Apr/2016:20:18:03] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:18:03] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 23, in addReadingValue
    def addReadingValue(session, readingValue, meterId):
NameError: global name 'date' is not defined
[24/Apr/2016:20:18:26] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:18:26] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 26, in addReadingValue
    newReading = session.query(Electricity).insert(id='NULL', value=readingValue,  readingDate=now, meterId = meterId)
NameError: global name 'Electricity' is not defined
[24/Apr/2016:20:18:53] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:18:53] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 26, in addReadingValue
    newReading = session.query(ElectricityInsert).insert(id='NULL', value=readingValue,  readingDate=now, meterId = meterId)
NameError: global name 'Electricity' is not defined
[24/Apr/2016:20:19:10] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:19:10] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 26, in addReadingValue
    newReading = session.query(ElectricityInsert).insert(id='NULL', value=readingValue,  readingDate=now, meterId = meterId)
AttributeError: 'Query' object has no attribute 'insert'
[24/Apr/2016:20:23:10] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:23:10] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 27, in addReadingValue
    sessiona.add(newReading)
NameError: global name 'sessiona' is not defined
[24/Apr/2016:20:23:41]  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/lib/tool/db.py", line 47, in commit_transaction
    cherrypy.engine.publish('commit-session')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 221, in publish
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', u\'12345\', datetime.date(2016, 4, 24), u\'1\')]',)
[24/Apr/2016:20:23:41] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:23:41] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 684, in respond
    self.hooks.run('on_end_resource')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', u\'12345\', datetime.date(2016, 4, 24), u\'1\')]',)
[24/Apr/2016:20:27:06] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:27:06] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 24, in addReadingValue
    now = date.today()
NameError: global name 'date' is not defined
[24/Apr/2016:20:27:59]  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/lib/tool/db.py", line 47, in commit_transaction
    cherrypy.engine.publish('commit-session')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 221, in publish
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', u\'12345\', \'YYYY-MM-DD HH:mm:ss\', u\'1\')]',)
[24/Apr/2016:20:27:59] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:27:59] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 684, in respond
    self.hooks.run('on_end_resource')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', u\'12345\', \'YYYY-MM-DD HH:mm:ss\', u\'1\')]',)
[24/Apr/2016:20:30:26]  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/lib/tool/db.py", line 47, in commit_transaction
    cherrypy.engine.publish('commit-session')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 221, in publish
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', u\'12345\', \'2016-04-24 00:00:00\', u\'1\')]',)
[24/Apr/2016:20:30:26] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:30:26] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 684, in respond
    self.hooks.run('on_end_resource')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', u\'12345\', \'2016-04-24 00:00:00\', u\'1\')]',)
[24/Apr/2016:20:32:17] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:32:17] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 24, in addReadingValue
    now = date.now()
AttributeError: type object 'datetime.date' has no attribute 'now'
[24/Apr/2016:20:33:00] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:33:00] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/webapp/app.py", line 120, in addNewReading
    ElectricityInsert.addReadingValue(db, inputJson['meterValue'], inputJson['meterId'])
  File "/mnt/external/weatherStation/weatherStationApp/lib/model/electricityInsert.py", line 24, in addReadingValue
    now = date.now()
NameError: global name 'date' is not defined
[24/Apr/2016:20:33:21]  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/lib/tool/db.py", line 47, in commit_transaction
    cherrypy.engine.publish('commit-session')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 221, in publish
    raise exc
ChannelFailures: InvalidRequestError("This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Instance <ElectricityInsert at 0xb5e58430> has a NULL identity key.  If this is an auto-generated value, check that the database table allows generation of new primary key values, and that the mapped Column object is configured to expect these generated values.  Ensure also that this flush() is not occurring at an inappropriate time, such aswithin a load() event.",)
[24/Apr/2016:20:33:21] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:33:21] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 684, in respond
    self.hooks.run('on_end_resource')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
ChannelFailures: InvalidRequestError("This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Instance <ElectricityInsert at 0xb5e58430> has a NULL identity key.  If this is an auto-generated value, check that the database table allows generation of new primary key values, and that the mapped Column object is configured to expect these generated values.  Ensure also that this flush() is not occurring at an inappropriate time, such aswithin a load() event.",)
[24/Apr/2016:20:34:01]  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/lib/tool/db.py", line 47, in commit_transaction
    cherrypy.engine.publish('commit-session')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 221, in publish
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', u\'12345\', \'2016-04-24 20:34:01\', u\'1\')]',)
[24/Apr/2016:20:34:01] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:34:01] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 684, in respond
    self.hooks.run('on_end_resource')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', u\'12345\', \'2016-04-24 20:34:01\', u\'1\')]',)
[24/Apr/2016:20:36:22]  
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/mnt/external/weatherStation/weatherStationApp/lib/tool/db.py", line 47, in commit_transaction
    cherrypy.engine.publish('commit-session')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/process/wspbus.py", line 221, in publish
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', \'12345\', \'2016-04-24 20:36:22\', \'1\')]',)
[24/Apr/2016:20:36:22] HTTP 
Request Headers:
  Content-Length: 36
  REFERER: http://192.168.1.183:7070/electricityUsage
  HOST: 192.168.1.183:7070
  ORIGIN: http://192.168.1.183:7070
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.194
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/json
  ACCEPT-ENCODING: gzip, deflate
[24/Apr/2016:20:36:22] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 684, in respond
    self.hooks.run('on_end_resource')
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
ChannelFailures: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) datatype mismatch [SQL: u\'INSERT INTO "powerConsumption" (id, value, "readingDate", "meterId") VALUES (?, ?, ?, ?)\'] [parameters: (\'NULL\', \'12345\', \'2016-04-24 20:36:22\', \'1\')]',)
